### ISSUE TITLE
Issue setting alarm

### ISSUE THREAD

**Issue by yakketyak** [FlipByBlink/FadeInAlarm_v2#1]
How do I set the alarm? For example, I set the alarm to 10:15am, but when I press the blue button the music starts playing immediately (it doesn’t wait until 10:15). If I don’t press the blue button the alarm does not go off.

**Comment by FlipByBlink** [comment]
App works correctly (maybe). 

> when I press the blue button the music starts playing immediately (it doesn’t wait until 10:15)

When you press the blue button the music starts playing immediately with "very small volume(0% ~10%)" (it doesn’t wait until 10:15am). App repeats playing the music. And when it is 10:15am, app starts to make the music bigger (to original volume) with taking a long time.

> If I don’t press the blue button the alarm does not go off.

Unfortunately, you must press blue button in advance. This spec is for complying with iOS limitations.

```
==== Japanese(native) ====

(おそらく)アプリは正常に動いています。

> when I press the blue button the music starts playing immediately (it doesn’t wait until 10:15)

ブルーボタンを押すと"とても小さな音量(0% ~10%)"で音楽が(10:15AMになる前ですが)流れ出します。アプリはずっと繰り返し再生します。そして10:15AMになると時間をかけて(本来の音量まで)少しずつ音量が大きくなります。

> If I don’t press the blue button the alarm does not go off.

残念ながら、このアプリではアラームを鳴らすために事前にブルーボタンを押す必要があります。この仕様はiOSの制限に準拠するためです。
```
